SELECT 
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    UI.GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS
ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 
    # DATE_FORMAT(OS.SALES_DATE, '%Y-%m'), UI.GENDER
    # DATE_FORMAT(OS.SALES_DATE, '%Y'),
    # DATE_FORMAT(OS.SALES_DATE, '%c'),
    YEAR(OS.SALES_DATE),
    MONTH(OS.SALES_DATE),
    UI.GENDER
ORDER BY YEAR, MONTH, UI.GENDER