SELECT 
    CONCAT(
        '/home/grep/src/', 
        FILE.BOARD_ID,
        '/',
        FILE.FILE_ID, 
        FILE.FILE_NAME, 
        FILE.FILE_EXT
    
    ) 
    AS FILE_PATH
    
FROM USED_GOODS_BOARD AS GOODS
JOIN USED_GOODS_FILE AS FILE
ON GOODS.BOARD_ID = FILE.BOARD_ID
WHERE GOODS.VIEWS IN (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE.FILE_ID DESC